<?php

namespace App\EventSubscriber;

use ImageKit\ImageKit;
use App\Entity\Picture;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use EasyCorp\Bundle\EasyAdminBundle\Event\AfterEntityPersistedEvent;
use EasyCorp\Bundle\EasyAdminBundle\Event\AfterEntityUpdatedEvent;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class UploadImageSubscriber implements EventSubscriberInterface
{
    // ImageKit.io API credentials from .env variables
    private $credentials;
    // parameterBag own all project environment constants
    protected $parameterBag;
    // entity manager for persisting picture url in database
    private $manager;

    public function __construct($credentials, ParameterBagInterface $parameterBag, EntityManagerInterface $manager)
    {
        $this->credentials = $credentials;
        $this->parameterBag = $parameterBag;
        $this->manager = $manager;
    }

    
    // method for registering for the desired events and launching the corresponding methods
    public static function getSubscribedEvents()
    {
        return [
            AfterEntityPersistedEvent::class => ['EntityPersistEvent'],
            AfterEntityUpdatedEvent::class => ['EntityUploadEvent'],
        ];
    }

    public function EntityPersistEvent(AfterEntityPersistedEvent $event)
    {
        $entity = $event->getEntityInstance();

        $this->uploadImage($entity);
    }
    
    public function EntityUploadEvent(AfterEntityUpdatedEvent $event)
    {
        $entity = $event->getEntityInstance();

        $this->uploadImage($entity);
    }

    // upload logic method
    public function uploadImage($entity)
    {
        // check if event corresponding to Picture entity
        if ($entity instanceof Picture) {
            
            // get the pth of the file just upload
            $filePath = $this->parameterBag->get('kernel.project_dir').'/public/images/upload/'.$entity->getUrl();
            
            // instance of imageKit with credentials
            $imageKit = new ImageKit(
                $this->credentials['publicKey'],
                $this->credentials['privateKey'],
                $this->credentials['urlEndpoint'],
            );
            
            // setting the imageKit url for setting the mane of the picture
            $imageUrl = $imageKit->url([
                'path' => '/'.$entity->getUrl()
            ]);

            // action to upload file in ImageKit's server
            $uploadFile = $imageKit->uploadFile([
                "file" => fopen($filePath, "r"),
                "fileName" => $entity->getUrl(),
            ]);
            
            // retrieve url generated by imagekit
            $url = json_decode(json_encode($uploadFile), true)['result']['url'];

            // set the url of picture entity
            $entity->setUrl($url);

            // save entity in database
            $this->manager->persist($entity);
            $this->manager->flush();

            // delete the file in server system
            $filesystem = new Filesystem();
            $filesystem->remove($filePath);

        }

        return;
    }

}